version = "3.8.3"
runner.dialect = scala213
maxColumn = 120
align.preset = more
assumeStandardLibraryStripMargin = true
docstrings.style = Asterisk
docstrings.wrap = no
indentOperator.preset = spray
lineEndings = preserve
newlines.avoidInResultType = true
newlines.alwaysBeforeElseAfterCurlyIf = false
newlines.beforeCurlyLambdaParams = multiline
newlines.afterCurlyLambdaParams = squash
newlines.inInterpolation = avoid
newlines.implicitParamListModifierForce = [before]
newlines.topLevelBodyIfMinStatements = []
newlines.topLevelStatementBlankLines = []
optIn.annotationNewlines = true
optIn.forceBlankLineBeforeDocstring = true
rewrite.rules = [AvoidInfix, Imports, PreferCurlyFors, RedundantBraces, RedundantParens, SortImports, SortModifiers]
rewrite.imports.sort = ascii
rewrite.imports.expand = false
rewrite.imports.groups = [
  ["java\\..*", "javax\\..*", "scala\\..*"],
  [".*"]
]
spaces.inImportCurlyBraces = true
trailingCommas = preserve